id: I53777E79
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W7494
  ocr_info:
    timestamp: 03/22/23T01:08:31
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-03-05 04:35:34.807986+00:00
last_modified: 2024-03-05 04:35:34.807991+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W7494
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW7494
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དེབ་ཐེར་སྔོན་པོ།
  languages:
  - bo
  author: འགོས་ལོ་ཙཱ་བ་གཞོན་ནུ་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.9569680338053297
  ocr_word_median_confidence_index: 1.0
bases:
  I3818:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3818
      total_pages: 972
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3818.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9569680338053297
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
